language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

env:
  global:
    - CC_TEST_REPORTER_ID=59a4077d0dfd3ee9d19efc4f213e7c7713e89ec4502745a1592467011ba0c3e5

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  # Initialise Composer
  - composer self-update -q
  - composer global require hirak/prestissimo

  # Installing Composer dependencies
  - composer install --no-interaction --no-suggest --optimize-autoloader

  # Installing code coverage tools
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT

script: vendor/bin/phpunit --coverage-clover clover.xml
